### ISSUE TITLE
Add provenance metadata (urls, timestamp) to zarr store

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#11]
Since we will likely tinker with different methods of retrieving the urls used for each dataset, I think it would be wise to add some of the 'baking' information to the written datasets. 

This requires upstream changes (https://github.com/pangeo-forge/pangeo-forge-recipes/issues/559)

Also consider to include: 
- like git hash of all the libraries

**Comment by cisaacstern** [comment]
Makes sense. I responded in https://github.com/pangeo-forge/pangeo-forge-recipes/issues/559#issuecomment-1670297136

**Comment by jbusecke** [comment]
Closed via addition of the `InjectAttrs` Stage from https://github.com/leap-stc/leap-data-management-utils/blob/92f6d5f29a6edf84fb36e82c947e2ab10a36d36d/leap_data_management_utils/data_management_transforms.py#L224-L255
