### ISSUE TITLE
Use Dataflow Prime to avoid memory issues?

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#16]
I discussed this with @cisaacstern at some point, and after reading about [Dataflow Prime](https://cloud.google.com/dataflow/docs/guides/enable-dataflow-prime) it seems this would be a perfect solution to deal with suspected OOM errors (see [the OOM comment here](https://github.com/leap-stc/cmip6-leap-feedstock/pull/9#issuecomment-1687560217) for discussion). 
Most jobs do not need a lot of memory, so defining large instances across all of them is wasteful. But there are some jobs that seem to be memory hungry (maybe those are netcdf3 files?), and having some means of giving them a bunch of memory sounds great. 
Any comments on how to enable Dataflow Prime within this workflow? Should this be an option on the `-action` and/or `-runner`? We probably have to both enable it, and provide resource resource hints:
> By default, memory scaling has an upper limit of 16 GiB (26 GiB when [using GPUs](https://cloud.google.com/dataflow/docs/gpu) and a lower limit of 6 GiB (12 GiB when using GPUs). Providing a resource hint can change both the upper and lower limits.

[source](https://cloud.google.com/dataflow/docs/vertical-autoscaling)

@yuvipanda do you have any thoughts on this?

**Comment by jbusecke** [comment]
An example of some of the jobs I am currently running: 
<img width="652" alt="image" src="https://github.com/leap-stc/cmip6-leap-feedstock/assets/14314623/299f7b31-b8a3-4ee5-8aba-26b91a3ffef8">

Def overkill on the memory here.

**Comment by yuvipanda** [comment]
@jbusecke runner already supports this! https://pangeo-forge-runner.readthedocs.io/en/latest/reference/bakery.html#pangeo_forge_runner.bakery.dataflow.DataflowBakery.use_dataflow_prime :) You can set that to true in your config and that should be enough.

**Comment by jbusecke** [comment]
Amazing! Thanks Yuvi!

**Comment by cisaacstern** [comment]
> maybe those are netcdf3 files?

Yes good bet they are.

Alternatively, you could use `OpenWithKerchunk` to load them lazily?

IIUC xarray (i.e. `scipy` backend) can't load NetCDF3 lazily, but kerchunk can.

**Comment by jbusecke** [comment]
Just [tried]() to enable prime, and the jobs are all reallly slow (taking about 1 hour)!
I noticed that vertical autoscaling does not seem to be enabled ( raised https://github.com/pangeo-forge/pangeo-forge-runner/issues/95). Is there a way to provide explicit flags in the runner config or do I have to wait for the above issue to be fixed?

> Alternatively, you could use OpenWithKerchunk to load them lazily?

Is that a drop-in replacement for `OpenWithXarray` or `OpenURLsWithFSSpec`?

**Comment by cisaacstern** [comment]
> Is that a drop-in replacement for OpenWithXarray or OpenURLsWithFSSpec?

It _should_ be able to be a drop in replacement for OpenURLsWithFSSpec, but it might need an additional adapter transform to realize that potential.

Currently it emits kerchunk references (a list of dicts), which xarray presumably won't understand. So we'd probably need:

OpenWithKerchunk | OpenKerchunkWithFSSpec | OpenWithXarray

Where OpenKerchunkWithFSSpec is a new transform that opens a set of kerchunk references with an fsspec reference file system.

**Comment by jbusecke** [comment]
Is there a way we can test this independently from the big CMIP6 recipe with some synthetic files? I am seeing a lot of flaky failures and would like to avoid development on that alpha-production recipe if that makes sense? Seems like this would be a pure `-recipes` issue for now?

**Comment by cisaacstern** [comment]
> Seems like this would be a pure -recipes issue for now?

Yes! https://github.com/pangeo-forge/pangeo-forge-recipes/issues/585

**Comment by jbusecke** [comment]
Oh it seems this one is working:
<img width="890" alt="image" src="https://github.com/leap-stc/cmip6-leap-feedstock/assets/14314623/ae3146b6-ae7b-4925-9943-0d93bb750751">

**Comment by cisaacstern** [comment]
> Oh it seems this one is working:

🤯 ...

...did you do anything different?

That's so cool!

**Comment by jbusecke** [comment]
Closed via #9
