### ISSUE TITLE
Use deploy action main

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#37]
Again currently we are using a PR brach of `-action`

Moving from #9: 

Merge https://github.com/pangeo-forge/deploy-recipe-action/pull/17 into main, and rebase in the gh workflow here.

Todo:
-[ ] Close #70

**Comment by cisaacstern** [comment]
Even better, we can use a release! 😃

**Comment by jbusecke** [comment]
Closed by #71
