### ISSUE TITLE
Label based runs not compatible with CMIP6 iids

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#5]
I just tried to add a label for #4 and tried to assign a tag with `run:CMIP6.CMIP.MRI.MRI-ESM2-0.historical.r3i1p1f1.day.pr.gn.v20190603`, but there seems to be a limit to the length of those tags 😬
<img width="361" alt="Screenshot 2023-08-02 at 18 12 11" src="https://github.com/leap-stc/cmip6-leap-feedstock/assets/14314623/f5a446ca-c976-47cf-a7bf-0f04968f12f0">

I guess this could be a broader issue with the label based execution, but particularly for this feedstock I think we need an alternative strategy.

cc @cisaacstern

**Comment by cisaacstern** [comment]
Here's one possible solution:

```python
import hashlib
iids = [
    'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515',
    'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r3i1p1f3.day.psl.gn.v20200507',
    'CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3.ssp585.r140i1p1f1.day.psl.gr.v20200412',
    'CMIP6.CMIP.IPSL.IPSL-CM5A2-INCA.historical.r1i1p1f1.Omon.zmeso.gn.v20200729',
]
iid_hashes = {hashlib.sha256(iid.encode()).hexdigest()[:7]: iid for iid in iids}
iid_hashes
```
```
{'ba6dd04': 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515',
 '74e2bee': 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r3i1p1f3.day.psl.gn.v20200507',
 '72f789b': 'CMIP6.ScenarioMIP.EC-Earth-Consortium.EC-Earth3.ssp585.r140i1p1f1.day.psl.gr.v20200412',
 'a44c71b': 'CMIP6.CMIP.IPSL.IPSL-CM5A2-INCA.historical.r1i1p1f1.Omon.zmeso.gn.v20200729'}
```

```yaml
recipes:
  - id: "ba6dd04"
    object: "..."  # depends on how the objects are stored
    description: 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515'
    provenance:  # ...
```

Then the label `run:ba6dd04` would run the recipe for iid 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515'.

On the one hand, I take the criticism that the hashes are less human readable.

On the other hand, they will be more immediately distinguishable from one-another than the highly similar iids which sometimes we need to squint at to distinguish from each other.

**Comment by cisaacstern** [comment]
Here's a further suggestion of how this repo could be organized:

```
...
├── feedstock
│   ├── _ba6dd04.py
│   ├── _74e2bee.py
│   ├── cmip6_transforms.py
│   ├── meta.yaml
│   └── requirements.txt
...
```

<details>
<summary>cmip6_transforms.py</summary>

```python
# cmip6_transforms.py

import apache_beam as beam
from pangeo_forge_recipes.transforms import OpenURLWithFSSpec, OpenWithXarray


class KeepOnlyVariableId(beam.PTransform):
    """Preprocessor."""
    ...


class OpenAndPreprocess(beam.PTransform):
    """Composite transform shared by all recipes in this feedstock."""

    def expand(self, pcoll: beam.PCollection) -> beam.PCollection:
        return (
            pcoll
            | OpenURLWithFSSpec()
            | OpenWithXarray(...)
            | KeepOnlyVariableId()
        )
```

</details>

<details>
<summary>_ba6dd04.py</summary>

```python
# _ba6dd04.py

"""
'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515' recipe.
The name of this module is the first seven characters of the hex digest of this iid.
"""
from pangeo_forge_recipes.patterns import pattern_from_file_sequence

from cmip6_transforms import OpenAndPreprocess


urls = [
    # actual urls for
    # 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515'
    # go inline here 
    "https://esgf.org/url/1",
    "https://esgf.org/url/2",
    ...
]

pattern = pattern_from_file_sequence(urls, ...)

_ba6dd04 = (
    beam.Create(pattern.items())
    | OpenAndPreprocess()
    | StoreToZarr(
        store_name='CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515.zarr',
        combine_dims=pattern.combine_dim_keys,
        target_chunk_size="200MB",
        target_chunks_aspect_ratio={...},
    )
)
```

</details>

<details>
<summary>meta.yaml</summary>


```
# meta.yaml
recipes:
  - id: "ba6dd04"
    object: "_ba6dd04:_ba6dd04"
    description: 'CMIP6.ScenarioMIP.MOHC.HadGEM3-GC31-MM.ssp585.r2i1p1f3.day.psl.gn.v20200515'
    provenance:  # ...
```

</details>

**Comment by jbusecke** [comment]
Thanks @cisaacstern. This looks good to me, but I am worried about the bulk of adding a python module per dataset. Handling thousands of modules seems like a nightmare waiting to happen. 

If technically possible I would like to propose a slightly modified structure for the recipes (I really like the structure for the 'base transformations'). I would try to batch a number of iids e.g. by model, time frequency. We would have to see what makes most sense here as we scale up - but basically I am thinking that we can group datasets with similar challenges, e.g. daily output, together. 

this would somehow require us to create dict-object recipes in each file. I am not sure if that works with dataflow and naming (I remember there was a bug regarding this in pgf-runner?).

Lets chat about this later today, excited to move this forward.

**Comment by jbusecke** [comment]
Just for posteriority: [This](https://github.com/pangeo-forge/deploy-recipe-action/blob/256da2916b5f17f358c5e5b0442458645cadb9f0/action/deploy_recipe.py#L117-L123) is the bug I was talking about (mentioned in #6)

**Comment by jbusecke** [comment]
I think within #9 we are getting towards a nice structure for now. I do not believe that single iid labels will every be a feasible method to handle this data. Rather we need to define [batches](#9) of recipes and build in some logic to [log and not retry successful writes]()
