### ISSUE TITLE
Not able to trigger deploy-recipe-action without labels

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#6]
To circumvent #5 I tried to set `select_recipe_by_label` to false but [nothing was run](https://github.com/leap-stc/cmip6-leap-feedstock/actions/runs/5741351257/job/15561239845#step:5:52). 

I am not sure if this was as intended. Just wanted to note this. I guess for some of the discussed cases here we might not want to use labels at all so having this option might become relevant.

**Comment by cisaacstern** [comment]
Not certain why nothing was run, but there is a bug in `pangeo-forge-runner` which will prevent this from working, see comment in action here:

> https://github.com/pangeo-forge/deploy-recipe-action/blob/256da2916b5f17f358c5e5b0442458645cadb9f0/action/deploy_recipe.py#L117-L123

**Comment by jbusecke** [comment]
Ah that makes sense and will also be important for what I described [here](https://github.com/leap-stc/cmip6-leap-feedstock/issues/5#issuecomment-1667722646)

**Comment by jbusecke** [comment]
The issue is that in [this line](https://github.com/pangeo-forge/deploy-recipe-action/blob/256da2916b5f17f358c5e5b0442458645cadb9f0/action/deploy_recipe.py#L53) will evaluate to true with either `true` or `false` input.

**Comment by jbusecke** [comment]
Closed via #9
