### ISSUE TITLE
Catalog Parsing is broken

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#60]
There seems to be a [permission issue](https://github.com/leap-stc/cmip6-leap-feedstock/actions/runs/6834072644/job/18586498268#step:6:20). I wonder if that has something to do with the lock down of `leap-persistent-ro` by @yuvipanda?  Not an urgent issue for now, just flagging it.

**Comment by yuvipanda** [comment]
@jbusecke is the primary goal of the `leap-persistent-ro` bucket pangeo-forge related stuff? I think in that case, what we should really do is to just take it out of the 2i2c terraform and have you hand manage it. If there is code elsewhere (like here) that is making changes to the configuration of the bucket, I don't think it can be really managed by us.

**Comment by jbusecke** [comment]
I have been revising my thinking about this (especially after the large egress charges we encountered recently). My current thinking:
- I think this particular issue will be resolved with #33 (I will integrate the catalog there)
- For pangeo-forge generated datasets within LEAP (e.g. via [data-management](https://github.com/leap-stc/data-management)) I currently am thinking about a 2 timescale strategy: 
    - Make `leap-persistent-ro` requester-pays (short term enables folks to get the data but they have to pay)
    - Medium/Long Term: Redirect this data to an OSN pod. I am currently evaluating how/when we can purchase one of those so the time scale is a bit unclear. 
    - We can also consider asking @cisaacstern if we can temporarily redirect the recipes to the pangeo-forge OSN bucket. 
Does that sound reasonable to you?

**Comment by jbusecke** [comment]
Closed via #89
