### ISSUE TITLE
LocalDirectBakery does not recognize previously cached files?

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#7]
It seems that each time I run a local test of a recipe it seems like the cached files are re-downloaded. Wondering if this is expected behavior. 

Just noting this down as it presents quite a bit of friction for me right now (might be alleviated once back in the US with better internet).

**Comment by cisaacstern** [comment]
Certainly I would expect locally cached files to be recognized (and not re-downloaded). 

When the caching logic checks to see if a file is cached, it does query the remote file to check its size, here:

> https://github.com/pangeo-forge/pangeo-forge-recipes/blob/a22e6aafc938be05809b55d9a3fced5598e71698/pangeo_forge_recipes/storage.py#L177-L183

So some networking is still required, even to use a local cache.


Questions:
1. What do the logs show for you when you've seen this problem?
2. What config file are you using?
3. Are you sure you've called `pangeo-forge-runner` from the same scratch directory in which files were previously cached, when you've observed this? If the cached file config is a relative path, and then `pangeo-forge-runner` is invoked in a different scratch directory (which lacks that relative path), the files will be re-downloaded.

**Comment by jbusecke** [comment]
I have seen this work successfully on the leap-hub, which makes me think this is not a problem on the pgf side. I will this to the flintstone like internet connection (maybe the files never finished downloading in the first place) here in Germany.
