### ISSUE TITLE
Accessing data has slowed down

### ISSUE THREAD

**Issue by ks905383** [leap-stc/cmip6-leap-feedstock#78]
Recently, my standard workflow for downloading / accessing CMIP6 data in the cloud has gotten seemingly ~ 1 order of magnitude slower. I don't have exact benchmarking for how it used to be, but the following code now takes ~ minutes when it used to take ~seconds. This shift happened a few weeks ago (not quite sure exactly when - I was recently recommended to mention this problem here). 

It's of course possible this is my machine / my connection, though I've tried it in a few different configurations with the same result. 

Is anyone else running into a similar issue? 

```
import xarray as xr
import pandas as pd
from tqdm.notebook import tqdm
import intake
import gcsfs
import warnings 

# Access google cloud storage links
fs = gcsfs.GCSFileSystem(token='anon', access='read_only')
# Get info about CMIP6 datasets
cmip6_datasets = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')

data_params = {'source_id':'ACCESS-CM2',
               'experiment_id':'historical',
               'member_id':'r1i1p1f1',
               'variable_id':'ua',
               'table_id':'Amon'}

# Get subset based on the data params above
cmip6_sub = cmip6_datasets.query(' and '.join([k+" == '"+data_params[k]+"'" for k in data_params.keys() if k != 'other']))
 
for row in tqdm([row for row in cmip6_sub.iterrows()]):
    url = row[1].zstore
    
    # Open dataset
    ds = xr.open_zarr(fs.get_mapper(url),consolidated=True)
    
    # Some small subset
    ds = ds.sel({'lat':slice(-5,5),'lon':slice(-10,30),'plev':slice(1000e2,500e2)})
    ds.load()
                
    # THIS TOOK 3:27 on my machine, 3:35 without the `.sel()` subset. 
```

**Comment by norlandrhagen** [comment]
Hey there @ks905383, I'm not sure about the new slowdown, but was wondering if you need the `ds.load()` call in your workflow? 

Running the subset without .load and specifying `chunks={}` to get dask backed arrays runs nearly instantaneously for me. 


```
ds = xr.open_zarr(fs.get_mapper(url),consolidated=True, chunks={})
# Some small subset
ds = ds.sel({'lat':slice(-5,5),'lon':slice(-10,30),'plev':slice(1000e2,500e2)})
# ds.load()
```

<img width="964" alt="image" src="https://github.com/leap-stc/cmip6-leap-feedstock/assets/22455466/4c6192c8-4fb4-47bd-8fde-1e3a9d67ff20">


@jbusecke probably can provide more insight into the `gcs` stuff!

**Comment by norlandrhagen** [comment]
@ks905383 good to know! If you want to get any of those datasets up on the cloud, happy to help pushing them through pangeo-forge-recipes in the future.

**Comment by jbusecke** [comment]
Just ran your code on the LEAP hub and it runs in ~10s

<img width="1006" alt="image" src="https://github.com/leap-stc/cmip6-leap-feedstock/assets/14314623/11d345ad-d931-43a8-908d-dd727ee5e4ef">

From this I conclude that whatever has changed must have been on the network/your_local_machine side

**Comment by ks905383** [comment]
@jbusecke thanks for the benchmark - I'll take it up with our sysadmins then!
