### ISSUE TITLE
Create MRE for rechunking failure

### ISSUE THREAD

**Issue by jbusecke** [leap-stc/cmip6-leap-feedstock#8]
Just a separate issue to track this.               

- [ ] Make a MRE for this bug and submit an issue about this.

I was able to reproduce the failure above for both iids used when I set the `target_chunks={..., 'bnds':1}` (tested with multiple values for the other dims). If I set `target_chunks={..., 'bnds':2}` I have so far not observed a single failure. I have traced back most failures with the dynamic chunking to this pattern too, and thus conclude this is not an issue with the dynamic chunking, but instead reveals some issues further upstream. My hint from above about the dimension having coordinates/no coordinates seemed to have been a wrong lead too. There is something is still going wrong with the rechunking if the dataset has dimensions on coordinates which are not present on the data_variable.

_Originally posted by @jbusecke in https://github.com/leap-stc/cmip6-leap-feedstock/issues/4#issuecomment-1666490146_

**Comment by jbusecke** [comment]
I think this is being tackled in https://github.com/pangeo-forge/pangeo-forge-recipes/issues/520

**Comment by cisaacstern** [comment]
Yes and also the linked https://github.com/pangeo-forge/pangeo-forge-recipes/pull/658

**Comment by jbusecke** [comment]
I think this was solved in #95.
